{"trial_id": "0078", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "filters_index", "default": null, "conditions": [], "min_value": 0, "max_value": 3, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_index", "default": null, "conditions": [], "min_value": 0, "max_value": 3, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activations", "default": "relu", "conditions": [], "values": ["relu", "leaky_relu", "tanh"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "L1", "default": 0.0, "conditions": [], "values": [0.0, 0.1, 0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "L2", "default": 0.0, "conditions": [], "values": [0.0, 0.1, 0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.5, "step": 0.05, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "spatial_dropout_rate", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.5, "step": 0.05, "sampling": "linear"}}], "values": {"filters_index": 3, "dense_index": 1, "activations": "tanh", "L1": 0.1, "L2": 0.0001, "dropout_rate": 0.15000000000000002, "spatial_dropout_rate": 0.30000000000000004, "tuner/epochs": 10, "tuner/initial_epoch": 0, "tuner/bracket": 1, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/asyncio/base_events.py\", line 608, in run_forever\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/asyncio/events.py\", line 84, in _run\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_53050/562131245.py\", line 8, in <module>\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 318, in fit\n\n  File \"/home/zyler/MachineLearningProjects/MedMNIST-Pneumonia/.conda/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 121, in one_step_on_iterator\n\nOut of memory while trying to allocate 238428072 bytes.\n\t [[{{node StatefulPartitionedCall}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_one_step_on_iterator_403170]\n"}